"""User Task

Revision ID: 9ad6d599d86e
Revises: ec00fdf1739a
Create Date: 2025-08-12 12:26:50.077538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad6d599d86e'
down_revision: Union[str, None] = 'ec00fdf1739a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('staus', sa.String(), nullable=False))
    op.drop_column('tasks', 'status')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(), nullable=False))
    op.drop_column('tasks', 'staus')
    # ### end Alembic commands ###
