"""User Task

Revision ID: acc4069eae87
Revises: 9ad6d599d86e
Create Date: 2025-08-12 12:35:04.243745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc4069eae87'
down_revision: Union[str, None] = '9ad6d599d86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('tasks', 'staus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('staus', sa.VARCHAR(), nullable=False))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
